### ISSUE TITLE
Doesn't work for blender 2.92.

### ISSUE THREAD

**Issue by arcdipesh** [importbpy/Floorboard-Generator#5]
I tried this addon with blender 2.92 but it wont show in addons after i install.

**Comment by oliiix** [comment]
yes I can confirm that. I installed it but nothing showed up. in the zip file there's a folder and the *init*.py file

**Comment by Andrej730** [comment]
Try to install https://github.com/importbpy/Floorboard-Generator/blob/master/Floor_Board_Generator.py, not the .zip file

**Comment by importbpy** [comment]
This repository is a mess. I will try to clean it up a bit :)

**Comment by importbpy** [comment]
I made a small refactor of this addon. You can download the zipped addon in the link bellow.
https://github.com/importbpy/Floorboard-Generator/releases/latest/download/Floorboard-Generator.zip
